// This file is auto-generated by TanStack Router
// It will be regenerated when running the dev server

// Placeholder route tree - will be generated by TanStack Router
export const routeTree = {} as any
